### ISSUE TITLE
missing artifact in maven central for semp-monitoring

### ISSUE THREAD

**Issue by kiranonly** [SolaceLabs/solace-ecs-scaler#1]
could not find artifactory for following maven co-ordinates
<dependency>
      <groupId>com.solace</groupId>
      <artifactId>semp-monitoring-client</artifactId>
      <version>1.0.0</version>
    </dependency>

**Comment by kiranonly** [comment]
@dennis-brinley - forgot to tag you :-)

**Comment by dennis-brinley** [comment]
@kiranonly - I built the semp-monitoring-client locally from SEMPv2 rest doc. I removed the dependency and substituted a new class to parse the queue statistics returned from SEMP call. This issue should be resolved. Please pull the updated code and retry.
